### ISSUE TITLE
Issues when publishing images on GHCR due to uppercase letters

### ISSUE THREAD

**Issue by Androoideka** [devcontainers/action#103]
Hi, I was using the feature-starter setup to publish the features I've made to GitHub automatically through GitHub Actions but was unable to because namespaces don't support uppercase characters. For more context, the log during deploy says "Failed to get upload session ID", but the workflow is still marked as successful. There are no packages uploaded after the workflow run.

I've confirmed that the uppercase characters are the problem by attempting the process locally through the devcontainer CLI. Currently I am publishing features manually through the CLI by writing out the namespace in lowercase (e.g androoideka/container-setups), but it'd be convenient if this action also supported it. Since the action builds the namespace through GitHub metadata, I'm guessing the simplest way to solve this is to change lines 21 and 22 in utils.ts by appending toLowerCase() to both github.context.repo.owner and github.context.repo.repo

Thanks!

**Comment by joshspicer** [comment]
Thanks for taking the time to report this.  The last couple days we've made some changes to mitigate this uppercase issue (more context on that https://github.com/oras-project/oras/issues/679):

- https://github.com/devcontainers/action/pull/105 (don't falsely mark as successful)
- https://github.com/devcontainers/cli/pull/293 (always downcase identifiers)

Changing this internally in the CLI should mean that we don't need the suggested change in the Action 

It's a good callout with that error message, i'm currently not reading the response from the registry, so while in your case it was due to the capitalization, it would be useful to actually print what the registry responded with. (https://github.com/devcontainers/cli/blob/8ddcefba00091f7463d4e4048124581d28b9d0c1/src/spec-configuration/containerCollectionsOCIPush.ts#L56)

I'll leave this open until the change is deployed and you can validate it works as expected. Thanks!
